### ISSUE TITLE
求分享

### ISSUE THREAD

**Issue by X1AOX1A** [Holy-Shine/Introduciton-2-ML-with-Python-notebook#1]
你好，我最近也在学这本书，但一直找不到中文版的jupyter notebook，而书里提供的GIthub地址文件我一直无法下载，不知道您可不可以分享一下呢？

**Comment by Holy-Shine** [comment]
@X1AOX1A Hi你好。首先这个notebook是我自己整理的，目前也没啥时间更新。第二个问题的话，你是具体哪个部分的代码没法下载呢？

**Comment by X1AOX1A** [comment]
谢谢回复！我之前通过官方的Github下载速率太慢，现在已经通过其他人的Github下载成功了。

**Comment by Holy-Shine** [comment]
@X1AOX1A :smile: Well done！
